<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.samsepiol</groupId>
        <artifactId>bom</artifactId>
        <version>0.0.3-BOM-SNAPSHOT</version>
        <relativePath/>
    </parent>
    <groupId>com.samsepiol.library</groupId>
    <artifactId>library-root</artifactId>
    <version>0.0.2-LIBRARY-SNAPSHOT</version>
    <name>samsepiol-library</name>
    <packaging>pom</packaging>
    <description>samsepiol-library</description>

    <modules>
        <module>library-core</module>
        <module>http</module>
        <module>temporal</module>
        <module>library-application</module>
        <module>mongo</module>
    </modules>

</project>
