<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.samsepiol.library</groupId>
        <artifactId>library-root</artifactId>
        <version>0.0.2-LIBRARY-SNAPSHOT</version>
    </parent>

    <artifactId>library-application</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>

        <dependency>
            <groupId>com.samsepiol.library</groupId>
            <artifactId>library-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.samsepiol.library</groupId>
            <artifactId>mongo</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.samsepiol.library</groupId>
            <artifactId>cache</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.samsepiol.library</groupId>
            <artifactId>message-queue</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>com.samsepiol.library</groupId>
            <artifactId>temporal</artifactId>
            <version>${project.version}</version>
        </dependency>

    </dependencies>

    <properties>
        <project.mainClass>com.samsepiol.library.application.LibraryApplication</project.mainClass>
    </properties>

</project>