spring:
  application:
    name: samsepiol-library
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 6969